[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_22"]

[deploy]
startCommand = "node dist/server/server.js"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
