[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_22"]

[deploy]
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
