/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateGroupRouteImport } from './routes/create-group'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupSlugIndexRouteImport } from './routes/groups/$groupSlug/index'
import { Route as GroupsGroupSlugStatsRouteImport } from './routes/groups/$groupSlug/stats'
import { Route as GroupsGroupSlugAddEntryRouteImport } from './routes/groups/$groupSlug/add-entry'
import { Route as GroupsGroupSlugEditEntryEntryIdRouteImport } from './routes/groups/$groupSlug/edit-entry/$entryId'

const CreateGroupRoute = CreateGroupRouteImport.update({
  id: '/create-group',
  path: '/create-group',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupSlugIndexRoute = GroupsGroupSlugIndexRouteImport.update({
  id: '/groups/$groupSlug/',
  path: '/groups/$groupSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupSlugStatsRoute = GroupsGroupSlugStatsRouteImport.update({
  id: '/groups/$groupSlug/stats',
  path: '/groups/$groupSlug/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupSlugAddEntryRoute = GroupsGroupSlugAddEntryRouteImport.update({
  id: '/groups/$groupSlug/add-entry',
  path: '/groups/$groupSlug/add-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupSlugEditEntryEntryIdRoute =
  GroupsGroupSlugEditEntryEntryIdRouteImport.update({
    id: '/groups/$groupSlug/edit-entry/$entryId',
    path: '/groups/$groupSlug/edit-entry/$entryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-group': typeof CreateGroupRoute
  '/groups/$groupSlug/add-entry': typeof GroupsGroupSlugAddEntryRoute
  '/groups/$groupSlug/stats': typeof GroupsGroupSlugStatsRoute
  '/groups/$groupSlug/': typeof GroupsGroupSlugIndexRoute
  '/groups/$groupSlug/edit-entry/$entryId': typeof GroupsGroupSlugEditEntryEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-group': typeof CreateGroupRoute
  '/groups/$groupSlug/add-entry': typeof GroupsGroupSlugAddEntryRoute
  '/groups/$groupSlug/stats': typeof GroupsGroupSlugStatsRoute
  '/groups/$groupSlug': typeof GroupsGroupSlugIndexRoute
  '/groups/$groupSlug/edit-entry/$entryId': typeof GroupsGroupSlugEditEntryEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-group': typeof CreateGroupRoute
  '/groups/$groupSlug/add-entry': typeof GroupsGroupSlugAddEntryRoute
  '/groups/$groupSlug/stats': typeof GroupsGroupSlugStatsRoute
  '/groups/$groupSlug/': typeof GroupsGroupSlugIndexRoute
  '/groups/$groupSlug/edit-entry/$entryId': typeof GroupsGroupSlugEditEntryEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-group'
    | '/groups/$groupSlug/add-entry'
    | '/groups/$groupSlug/stats'
    | '/groups/$groupSlug/'
    | '/groups/$groupSlug/edit-entry/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-group'
    | '/groups/$groupSlug/add-entry'
    | '/groups/$groupSlug/stats'
    | '/groups/$groupSlug'
    | '/groups/$groupSlug/edit-entry/$entryId'
  id:
    | '__root__'
    | '/'
    | '/create-group'
    | '/groups/$groupSlug/add-entry'
    | '/groups/$groupSlug/stats'
    | '/groups/$groupSlug/'
    | '/groups/$groupSlug/edit-entry/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateGroupRoute: typeof CreateGroupRoute
  GroupsGroupSlugAddEntryRoute: typeof GroupsGroupSlugAddEntryRoute
  GroupsGroupSlugStatsRoute: typeof GroupsGroupSlugStatsRoute
  GroupsGroupSlugIndexRoute: typeof GroupsGroupSlugIndexRoute
  GroupsGroupSlugEditEntryEntryIdRoute: typeof GroupsGroupSlugEditEntryEntryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-group': {
      id: '/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof CreateGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupSlug/': {
      id: '/groups/$groupSlug/'
      path: '/groups/$groupSlug'
      fullPath: '/groups/$groupSlug/'
      preLoaderRoute: typeof GroupsGroupSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupSlug/stats': {
      id: '/groups/$groupSlug/stats'
      path: '/groups/$groupSlug/stats'
      fullPath: '/groups/$groupSlug/stats'
      preLoaderRoute: typeof GroupsGroupSlugStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupSlug/add-entry': {
      id: '/groups/$groupSlug/add-entry'
      path: '/groups/$groupSlug/add-entry'
      fullPath: '/groups/$groupSlug/add-entry'
      preLoaderRoute: typeof GroupsGroupSlugAddEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupSlug/edit-entry/$entryId': {
      id: '/groups/$groupSlug/edit-entry/$entryId'
      path: '/groups/$groupSlug/edit-entry/$entryId'
      fullPath: '/groups/$groupSlug/edit-entry/$entryId'
      preLoaderRoute: typeof GroupsGroupSlugEditEntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateGroupRoute: CreateGroupRoute,
  GroupsGroupSlugAddEntryRoute: GroupsGroupSlugAddEntryRoute,
  GroupsGroupSlugStatsRoute: GroupsGroupSlugStatsRoute,
  GroupsGroupSlugIndexRoute: GroupsGroupSlugIndexRoute,
  GroupsGroupSlugEditEntryEntryIdRoute: GroupsGroupSlugEditEntryEntryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
